<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
    <title>Account Created</title>
    <link rel="stylesheet" href="UiUIKit_stylesheets/iphone.css" />
    <link rel="stylesheet" href="css/style.css" />
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png" />
    <script type="text/javascript" charset="utf-8">
            window.onload = function() {
              setTimeout(function(){window.scrollTo(0, 1);}, 100);
            }
    </script>


    <!-- end line customization -->
</head>

<body>

<!--    Informs the user that the account has been made
    A button redirects them to the login screen-->
    <div id="infopage">
        <ul class="profile">
            <h2 align="center">Account Created</h2>
        </ul>

        <ul class="data">
            <li><p>Push the Button Below to Return to the Login Screen.</p></li>
        </ul>

        <a href="login.php" id="submit" >Login Screen</a>

        <br />
        <br />
        <h4><i>You may edit the information entered when logged in.</i></h4>
    </div>
</body>
</html>