<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="yes" name="apple-mobile-web-app-capable" />
<meta content="index,follow" name="robots" />
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<link href="pics/homescreen.gif" rel="apple-touch-icon" />
<meta content="minimum-scale=1.0, width=device-width, maximum-scale=0.6667, user-scalable=no" name="viewport" />
<link href="css/style.css" rel="stylesheet" media="screen" type="text/css" />
<script src="javascript/functions.js" type="text/javascript"></script>
<title>Feedback Sent</title>
<link href="pics/startup.png" rel="apple-touch-startup-image" />
<meta content="iPod,iPhone,Webkit,iWebkit,Website,Create,mobile,Tutorial,free" name="keywords" />
<meta content="CSS3 is at the core of the new iwebkit. It makes everything live and move. Learn more about the technology on this page" name="description" />
<meta http-equiv="refresh" content="5; URL=home.php" />
</head>

<body>

<div id="topbar">

</div>

<!--    Show button to return to homescreen-->
    <div id="content">

	<ul class="pageitem">
		<li class="textbox"><span class="header" align="center">Feedback Sent!</span>
                    <p>Your request for for assistance has been sent to an administrator.  Press the button below to return to Home Screen. You will be redirected in 5 seconds.</p>
		</li>
	</ul>
    <a href="home.php" id="submit" >Home</a>
</div>

</body>

</html>
