<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta content="yes" name="apple-mobile-web-app-capable" />
<meta content="index,follow" name="robots" />
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<link href="pics/homescreen.gif" rel="apple-touch-icon" />
<meta content="minimum-scale=1.0, width=device-width, maximum-scale=0.6667, user-scalable=no" name="viewport" />
<link href="css/style.css" rel="stylesheet" media="screen" type="text/css" />
<script src="javascript/functions.js" type="text/javascript"></script>
<title>Home</title>
<meta content="iPod,iPhone,Webkit,iWebkit,Website,Create,mobile,Tutorial,free" name="keywords" />
<meta content="now completly styles thanks to css these form elements are lighter and easier to use than ever before." name="description" />
        <link rel="stylesheet" href="css/system.css" type="text/css" media="screen" />
    </head>
    <body>
<!--        Navigation elements-->
        <div id="topbar">
	<div id="title">
		Home</div>
	<div id="leftbutton">
		<a href="feedback.php" class="noeffect">Feedback</a> </div>
        <div id="rightnav">
		<a href="logout.php">Logout</a></div>
        </div>

        
        

<!--Navigation drilldown links-->
<div id="content">
	<ul class="pageitem">
		<li class="textbox"><span class="header">Trillium</span><p>
		Use the menu below to browse and edit the sections of this app.</p>
		</li>
		<li class="menu"><a href="students.php">
		<img alt="list" src="thumbs/students.png" /><span class="name">Students</span><span class="arrow"></span></a></li>
		<li class="menu"><a href="advisorInfo.php">
		<img alt="wordpress" src="thumbs/advisor.png" /><span class="name">Advisor Information</span><span class="arrow"></span></a></li>
		<li class="menu"><a href="chapterInfo.php">
		<img alt="music" src="thumbs/chapter.png" /><span class="name">Chapter Information</span><span class="arrow"></span></a></li>
		<li class="menu"><a href="http://www.deca.org/competitions/2/">
		<img alt="store" src="thumbs/competitions.png" /><span class="name">Compeititve Events Listing</span><span class="arrow"></span></a></li>
		</ul>
		<ul class="pageitem">
			<li class="info"><p>The 'Competitive Events Listings' link will redirect you to an external webpage.</p></li>
		</ul>
</div>

</body>

</html>
