<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="css/style.css" rel="stylesheet" media="screen" type="text/css" />
        <link rel="stylesheet" href="css/system.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="css/login.css" type="text/css" media="screen" />
        <meta content="yes" name="apple-mobile-web-app-capable" />
<meta content="index,follow" name="robots" />
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<link href="pics/homescreen.gif" rel="apple-touch-icon" />
<meta content="minimum-scale=1.0, width=device-width, maximum-scale=0.6667, user-scalable=no" name="viewport" />
<link href="css/style.css" rel="stylesheet" media="screen" type="text/css" />
<script src="javascript/functions.js" type="text/javascript"></script>
<title>Home</title>
<meta content="iPod,iPhone,Webkit,iWebkit,Website,Create,mobile,Tutorial,free" name="keywords" />
<meta content="now completly styles thanks to css these form elements are lighter and easier to use than ever before." name="description" />
    </head>
    <body>
        <br>
        <br>
<!--        Display welcome message and button to the login screen-->
<h1 align="center">Welcome to Trillium.</h1>
    <br><br><br>
                <h4 align="center">Click below to Login.</h4>
                <a href="login.php" id="submit" >Login Screen</a>

    </body>
</html>
