<?php

/**
 * levelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class levelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object levelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('level');
    }
}