<?php

/**
 * observationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class observationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object observationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('observation');
    }
}