<?php

/**
 * ObservationSkillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObservationSkillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObservationSkillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObservationSkill');
    }
}