<?php

/**
 * skillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class skillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object skillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('skill');
    }
}