<?php

/**
 * StudentKlassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentKlassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentKlassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentKlass');
    }
}