<?php

/**
 * teacherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class teacherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object teacherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('teacher');
    }
}