<?php

/**
 * Baseskill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $description
 * @property Doctrine_Collection $observation_has_skills
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getName()                   Returns the current record's "name" value
 * @method clob                getDescription()            Returns the current record's "description" value
 * @method Doctrine_Collection getObservationHasSkills()   Returns the current record's "observation_has_skills" collection
 * @method skill               setId()                     Sets the current record's "id" value
 * @method skill               setName()                   Sets the current record's "name" value
 * @method skill               setDescription()            Sets the current record's "description" value
 * @method skill               setObservationHasSkills()   Sets the current record's "observation_has_skills" collection
 * 
 * @package    skills
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseskill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skill');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => 65535,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ObservationSkill as observation_has_skills', array(
             'local' => 'id',
             'foreign' => 'skill_id'));
    }
}