<?php

/**
 * Baselevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $description
 * @property Doctrine_Collection $observation_has_skills
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getCode()                   Returns the current record's "code" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method Doctrine_Collection getObservationHasSkills()   Returns the current record's "observation_has_skills" collection
 * @method level               setId()                     Sets the current record's "id" value
 * @method level               setCode()                   Sets the current record's "code" value
 * @method level               setDescription()            Sets the current record's "description" value
 * @method level               setObservationHasSkills()   Sets the current record's "observation_has_skills" collection
 * 
 * @package    skills
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('level');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ObservationSkill as observation_has_skills', array(
             'local' => 'id',
             'foreign' => 'level_id'));
    }
}