<?php

/**
 * Baseobservation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property clob $comment
 * @property integer $student_id
 * @property integer $teacher_id
 * @property integer $klass_id
 * @property student $student
 * @property teacher $teacher
 * @property klass $klass
 * @property Doctrine_Collection $observation_has_skills
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method clob                getComment()                Returns the current record's "comment" value
 * @method integer             getStudentId()              Returns the current record's "student_id" value
 * @method integer             getTeacherId()              Returns the current record's "teacher_id" value
 * @method integer             getKlassId()                Returns the current record's "klass_id" value
 * @method student             getStudent()                Returns the current record's "student" value
 * @method teacher             getTeacher()                Returns the current record's "teacher" value
 * @method klass               getKlass()                  Returns the current record's "klass" value
 * @method Doctrine_Collection getObservationHasSkills()   Returns the current record's "observation_has_skills" collection
 * @method observation         setId()                     Sets the current record's "id" value
 * @method observation         setComment()                Sets the current record's "comment" value
 * @method observation         setStudentId()              Sets the current record's "student_id" value
 * @method observation         setTeacherId()              Sets the current record's "teacher_id" value
 * @method observation         setKlassId()                Sets the current record's "klass_id" value
 * @method observation         setStudent()                Sets the current record's "student" value
 * @method observation         setTeacher()                Sets the current record's "teacher" value
 * @method observation         setKlass()                  Sets the current record's "klass" value
 * @method observation         setObservationHasSkills()   Sets the current record's "observation_has_skills" collection
 * 
 * @package    skills
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseobservation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('observation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('comment', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => true,
             'length' => 65535,
             ));
        $this->hasColumn('student_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('teacher_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('klass_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_observation_student1', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
        $this->index('fk_observation_teacher1', array(
             'fields' => 
             array(
              0 => 'teacher_id',
             ),
             ));
        $this->index('fk_observation_klass1', array(
             'fields' => 
             array(
              0 => 'klass_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('student', array(
             'local' => 'student_id',
             'foreign' => 'id'));

        $this->hasOne('teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id'));

        $this->hasOne('klass', array(
             'local' => 'klass_id',
             'foreign' => 'id'));

        $this->hasMany('ObservationSkill as observation_has_skills', array(
             'local' => 'id',
             'foreign' => 'observation_id'));
    }
}