<?php

/**
 * BaseStudentKlass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $klass_id
 * @property student $student
 * @property klass $klass
 * 
 * @method integer      getStudentId()  Returns the current record's "student_id" value
 * @method integer      getKlassId()    Returns the current record's "klass_id" value
 * @method student      getStudent()    Returns the current record's "student" value
 * @method klass        getKlass()      Returns the current record's "klass" value
 * @method StudentKlass setStudentId()  Sets the current record's "student_id" value
 * @method StudentKlass setKlassId()    Sets the current record's "klass_id" value
 * @method StudentKlass setStudent()    Sets the current record's "student" value
 * @method StudentKlass setKlass()      Sets the current record's "klass" value
 * 
 * @package    skills
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentKlass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_has_klass');
        $this->hasColumn('student_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('klass_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_student_has_klass_student1', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
        $this->index('fk_student_has_klass_klass1', array(
             'fields' => 
             array(
              0 => 'klass_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('student', array(
             'local' => 'student_id',
             'foreign' => 'id'));

        $this->hasOne('klass', array(
             'local' => 'klass_id',
             'foreign' => 'id'));
    }
}