<?php

/**
 * Basestudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $student_id
 * @property string $first_name
 * @property string $last_name
 * @property Doctrine_Collection $observations
 * @property Doctrine_Collection $student_has_klasses
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getStudentId()           Returns the current record's "student_id" value
 * @method string              getFirstName()           Returns the current record's "first_name" value
 * @method string              getLastName()            Returns the current record's "last_name" value
 * @method Doctrine_Collection getObservations()        Returns the current record's "observations" collection
 * @method Doctrine_Collection getStudentHasKlasses()   Returns the current record's "student_has_klasses" collection
 * @method student             setId()                  Sets the current record's "id" value
 * @method student             setStudentId()           Sets the current record's "student_id" value
 * @method student             setFirstName()           Sets the current record's "first_name" value
 * @method student             setLastName()            Sets the current record's "last_name" value
 * @method student             setObservations()        Sets the current record's "observations" collection
 * @method student             setStudentHasKlasses()   Sets the current record's "student_has_klasses" collection
 * 
 * @package    skills
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basestudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('student_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('first_name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('last_name', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('observation as observations', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $this->hasMany('StudentKlass as student_has_klasses', array(
             'local' => 'id',
             'foreign' => 'student_id'));
    }
}