<?php

/**
 * BaseObservationSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $observation_id
 * @property integer $observation_student_id
 * @property integer $observation_teacher_id
 * @property integer $observation_klass_id
 * @property integer $skill_id
 * @property integer $level_id
 * @property observation $observation
 * @property skill $skill
 * @property level $level
 * 
 * @method integer          getObservationId()          Returns the current record's "observation_id" value
 * @method integer          getObservationStudentId()   Returns the current record's "observation_student_id" value
 * @method integer          getObservationTeacherId()   Returns the current record's "observation_teacher_id" value
 * @method integer          getObservationKlassId()     Returns the current record's "observation_klass_id" value
 * @method integer          getSkillId()                Returns the current record's "skill_id" value
 * @method integer          getLevelId()                Returns the current record's "level_id" value
 * @method observation      getObservation()            Returns the current record's "observation" value
 * @method skill            getSkill()                  Returns the current record's "skill" value
 * @method level            getLevel()                  Returns the current record's "level" value
 * @method ObservationSkill setObservationId()          Sets the current record's "observation_id" value
 * @method ObservationSkill setObservationStudentId()   Sets the current record's "observation_student_id" value
 * @method ObservationSkill setObservationTeacherId()   Sets the current record's "observation_teacher_id" value
 * @method ObservationSkill setObservationKlassId()     Sets the current record's "observation_klass_id" value
 * @method ObservationSkill setSkillId()                Sets the current record's "skill_id" value
 * @method ObservationSkill setLevelId()                Sets the current record's "level_id" value
 * @method ObservationSkill setObservation()            Sets the current record's "observation" value
 * @method ObservationSkill setSkill()                  Sets the current record's "skill" value
 * @method ObservationSkill setLevel()                  Sets the current record's "level" value
 * 
 * @package    skills
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObservationSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('observation_has_skill');
        $this->hasColumn('observation_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('observation_student_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('observation_teacher_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('observation_klass_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('skill_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('level_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_observation_has_skill_observation1', array(
             'fields' => 
             array(
              0 => 'observation_id',
              1 => 'observation_student_id',
              2 => 'observation_teacher_id',
              3 => 'observation_klass_id',
             ),
             ));
        $this->index('fk_observation_has_skill_skill1', array(
             'fields' => 
             array(
              0 => 'skill_id',
             ),
             ));
        $this->index('fk_observation_has_skill_level1', array(
             'fields' => 
             array(
              0 => 'level_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('observation', array(
             'local' => 'observation_id',
             'foreign' => 'id'));

        $this->hasOne('skill', array(
             'local' => 'skill_id',
             'foreign' => 'id'));

        $this->hasOne('level', array(
             'local' => 'level_id',
             'foreign' => 'id'));
    }
}